<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Error Occured</title>

<style type="text/css">
	.errStyle {
		border:solid 1px silver;
		padding:50px;
		width:300px;
		margin-top:10%;
	}
	body {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: x-small;	
	}
</style>
</head>

<body>
	<center>
	<div align="center" class="errStyle">
		<img src="images/webware.png" /><br /><br /><br /><br />
		
		<strong><font color="red">An unexpected error has occured</font></strong>
		<p>You may be able to <a href="javascript:history.back()">return to where you were</a> without losing your form data</p>
		<p>The error has been forwarded to our technical staff.<br /><br /><em>We apologize for any inconvenience this may have caused.</em></p>
		<p><a href="/home-redir.cfm">My Home Page</a></p>
	</div>
	</center>
	
	<cfoutput>
		<cfmail from="noreply@centerlineservices.biz" to="#error.mailTo#" subject="Center Line Services web site error" type="html">
		<h1>Site Error</h1>
		
		<strong>Generated by user:</strong> #session.username#<br />
		
		<cfdump var="#error#">
		</cfmail>
		
		<cfquery name="writeErrorLog" datasource="#session.datasource#">
			INSERT INTO 
			site_errors (userid, 
						 date, 
						 diagnostics,
						 browser,
						 remoteAddress,
						 HTTPReferer,
						 template,
						 queryString,
						 message,
						 type)
			VALUES (#session.userid#,
					#CreateODBCDateTime(error.DateTime)#,
					'#error.Diagnostics#',
					'#error.Browser#',
					'#error.RemoteAddress#',
					'#error.HTTPReferer#',
					'#error.Template#',
					'#error.QueryString#',
					'#error.message#',
					'#error.type#')
			
		</cfquery>
	</cfoutput>

</body>
</html>
